version: '3.3'

services:
  redis:
    image: 'redis:3.2.7'
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
      
    #volumes:
    #  - data01:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9200"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    restart: always
    ports:
      - 5601:5601
    links:
      - elasticsearch
  postgres:
    image: postgres:12.2
    volumes:
      - postgres:/var/lib/postgresql/data
    #  - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root              
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
#  webserver:
#    image: apache/airflow:latest
#    restart: always
#    depends_on:
#        - postgres
#    environment:
#        - LOAD_EX=y
#        - EXECUTOR=Local
#    volumes:
#        - ./dags:/usr/local/airflow/dags
#    ports:
#        - 8255:8255
#    command: webserver

  webserver:
    image: puckel-airflow-with-docker-inside:latest #puckel/docker-airflow:latest
    restart: always
    depends_on:
        - postgres
    volumes:
        - ./dags:/usr/local/airflow/dags # bind mount for airflow dags
        - ./requirements.txt:/requirements.txt
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 8222:8080               # airflow port
    command: webserver

    # airflow:
    #   image: puckel/docker-airflow:latest
    #   restart: always
    #   depends_on:
    #       - postgres
    #   volumes:
    #       - ./dags:/usr/local/airflow/dags # bind mount for airflow dags
    #   ports:
    #       - 8222:8080               # airflow port
    #   command: webserver

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080 #localhost:8888
  nifi:
    image: cgreen010/nifiwithdrivers:latest
    volumes:
      - nifi:/opt/nifi/nifi-current/state
      - nifi:/opt/nifi/nifi-current/repositories/database_repository
      - nifi:/opt/nifi/nifi-current/repositories/flowfile_repository
      - nifi:/opt/nifi/nifi-current/repositories/content_repository
      - nifi:/opt/nifi/nifi-current/repositories/provenance_repository
    #  - /home/chris/ubuntu/nifi/conf/data_2:/opt/nifi/nifi-current/conf
    #  - /home/chris/ubuntu/nifi/conf/postgres:/opt/nifi/nifi-current/lib
    #  - /tmp/nifi:/opt/nifi_in
    #  - ./extensions:/opt/nifi/nifi-current/extensions #avoid relational posistioning ./ needs to be /home/chris/
    ports:
      - 8080 # Unsecured HTTP Web Port
    links:
      - elasticsearch
      - postgres
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_HOME=/opt/nifi/nifi-current
      - NIFI_LOG_DIR=/opt/nifi/nifi-current/logs
      - NIFI_PID_DIR=/opt/nifi/nifi-current/run
      - NIFI_BASE_DIR=/opt/nifi
    restart: always
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   #restart: "no"
  #   ports:
  #       - "9000:9000"
  #   environment:
  #       KAFKA_BROKERCONNECT: "kafka:29092"
  #   depends_on:
  #       - "kafka"
  # kafka:
  #   image: wurstmeister/kafka
  #   depends_on:
  #       - zookeeper
  #   ports:
  #       - 9092:9092
  #   environment:
  #       KAFKA_BROKER_ID: 1
  #       KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
  #       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#  global_forcast:
#    image: cgreen010/hbtest:version1
#    restart: always
#    ports: 
#      - 8151
#    links:
#      - elasticsearch
#      - postgres
  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  flower:
    image: puckel-airflow-with-docker-inside:latest
    restart: always
    depends_on:
      - redis
    # environment:
    #   #- EXECUTOR=Celery
    #   # - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: puckel-airflow-with-docker-inside:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./plugins:/usr/local/airflow/plugins
    # environment:
    #   # - LOAD_EX=n
    #   # - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    #   # - EXECUTOR=Celery
    #   # - POSTGRES_USER=airflow
    #   # - POSTGRES_PASSWORD=airflow
    #   # - POSTGRES_DB=airflow
    #   # - REDIS_PASSWORD=redispass
    command: scheduler

  worker:
    image: puckel-airflow-with-docker-inside:latest
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # environment:
    #   - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    #   - EXECUTOR=Celery
    command: worker

    
volumes:
  postgres:
  nifi:
  openldap:
  metabase:
  pgadmin:
  global_forcast:





























